apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kaniko-build-
spec:
  entrypoint: main
  volumes:
  - name: docker-config
    secret:
      items:
      - key: .dockerconfigjson
        path: config.json
      secretName: docker-config
  templates:
  - name: main
    dag:
      tasks:
      - name: build-image
        templateRef:
          name: argo-hub.kaniko.0.0.1
          template: build
        arguments:
          parameters:
          - name: REPO
            value: 'https://github.com/nilofe/smp.git'
          - name: IMAGE_NAME
            value: 'nilofe/go'
          - name: GIT_TOKEN_SECRET
            value: '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'
