apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: trivy-scan-
spec:
  entrypoint: trivy-scan
  templates:
    - name: trivy-scan
      container:
        image: gcr.io/kaniko-project/executor:latest
        args: ["--dockerfile=Dockerfile", "--destination=hola:v1"]
        volumeMounts:
          - name: kaniko-secret
            mountPath: /secret
      volumes:
        - name: kaniko-secret
          secret:
            secretName: kaniko-secret
    - name: trivy-scan
      container:
        image: aquasec/trivy:latest
        args: ["image", "--format", "json", "hola:v1"]
