name: Go ci-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Build
        run: pwd ; cd smp/go-test/ ; go build -v ./...

      - name: Test
        run: go test

      - name: Hecho
        run: echo "goosd"

