name: Go ci-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Cambiar de carpeta
        run: cd go-test/

      - name: Descargar módulos
        run: go mod download

      - name: Build
        run: go build -o ./app/main

      - name: Hecho
        run: echo "goosd"

