apiVersion: argoproj.io/v1alpha1
kind: Template
metadata:
  name: build-job-example
container:
  image: debian:latest
  command: ["/bin/sh"]
  script: |
    apt update && apt upgrade -y && apt install git curl -y
    curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
    rm argocd-linux-amd64
    argocd login --insecure --grpc-web localhost:8080 --username admin --password Jd34iR6ecyl68iOv
    echo "listo papa"
  outputs:
    parameters:
      - name: output
        value: "build-job done"

